/*

 CHARACTERSPRITEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : C:\Users\User\Documents\charactersprite.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define characterspritemapWidth 4
#define characterspritemapHeight 4
#define characterspritemapBank 0

extern unsigned char characterspritemap[];

/* End of CHARACTERSPRITEMAP.H */
