/*

 CHARACTERSPRITEMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : C:\Users\User\Documents\charactersprite.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define characterspritemapWidth 4
#define characterspritemapHeight 4
#define characterspritemapBank 0

unsigned char characterspritemap[] =
{
  0x00,0x02,0x08,0x0A,0x01,0x03,0x09,0x0B,0x00,0x06,
  0x0C,0x0E,0x05,0x07,0x0D,0x0F
};

/* End of CHARACTERSPRITEMAP.C */
