/*

 SNAILLIFE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char snaillife[] =
{
  0x00,0x00,0x00,0x00,0x00,0x90,0x00,0x60,
  0x07,0x67,0x07,0x67,0x07,0x7F,0x00,0x00,

  0x81,0x81,0x42,0x42,0x24,0x24,0x18,0x18,
  0x18,0x18,0x18,0x18,0x18,0x18,0x3C,0x3C,
};

/* End of SNAILLIFE.C */
